---
# Capture the role of the hosts

# scs_virtual_hostname:                  "{{ sap_sid | lower }}scs{{ scs_instance_number }}cl1"
# ers_virtual_hostname:                  "{{ sap_sid | lower }}ers{{ ers_instance_number }}cl2"
# db_primary_hostname:
# db_secondary_hostname:

# - name:                                "Oracle Data Guard: Setting the primary and Secondary DB names"
#   ansible.builtin.set_fact:
#     db_primary:                       "{{ sap_sid | upper }}_DB[0] }}"         # Oracle Primary Host
#     db_secondary:                     "{{ sap_sid | upper }}_DB[1] }}"         # Oracle Secondary Host
  

