# Start HANA Database
# - name:                        "Stop SAP Central Services"
#   become:                       true
#   become_user:                  root
#   ansible.builtin.shell:       su -c "sapcontrol -nr {{ db_instance_number }} -function StopSystem" {{ db_sid |lower }}adm
#   register:                    sapsystem_stopped


# Check which node is currently Primary only if database_high_availability is true.


# Create the script for stop of database

#  Execute the script for database using SQL or DB command

#  Start the Oracle Database
- block:
  - name:                            "Create Oracle Primary Startup Script"
    become:                              true
    become_user:                         "oracle"
    ansible.builtin.blockinfile:
      create: true
      path: /etc/sap_deployment_automation/{{ db_sid | upper }}/startup_primary.sql
      marker_begin: "-- BEGIN"
      marker_end:   "-- END"
      block: |
           STARTUP;
           exit
      mode: '0755'

  - name:                     "Start Oracle Database"
    become:                    true
    become_user:               "oracle"
    ansible.builtin.shell:     

  - name:                                "ORACLE Start Oracle Database"
    become:                              true
    become_user:                         "oracle"
    ansible.builtin.shell: |
                                         set -o pipefail
                                         sqlplus / as sysdba @startup_primary.sql | tee startup.log
    register:                            dbstarted_results
    failed_when:                         dbstarted_results.rc != 0
    args:
      chdir:                             /etc/sap_deployment_automation/{{ db_sid | upper }}
      executable:                        /bin/csh
  when:
    - platform in ["ORACLE","ORACLE-ASM"]
    - sapops == "START"
  

#  Stop the oracle Database
- block:

  - name:                            "Create Oracle Primary Stop Script"
    become:                              true
    become_user:                         "oracle"
    ansible.builtin.blockinfile:
      create: true
      path: /etc/sap_deployment_automation/{{ db_sid | upper }}/stop_primary.sql
      marker_begin: "-- BEGIN"
      marker_end:   "-- END"
      block: |
           SHUTDOWN IMMEDIATE;
           exit
      mode: '0755'
    
  - name:                                "ORACLE Stop Oracle Database"
    become:                              true
    become_user:                         "oracle"
    ansible.builtin.shell: |
                                         set -o pipefail
                                         sqlplus / as sysdba @stop_primary.sql | tee stop.log
    register:                            dbstopped_results
    failed_when:                         dbstopped_results.rc != 0
    args:
      chdir:                             /etc/sap_deployment_automation/{{ db_sid | upper }}
      executable:                        /bin/csh
  when:
    - platform in ["ORACLE","ORACLE-ASM"]
    - sapops == "STOP"
  

