---
# Start the VMs in the resource group
- name:                            "Start the Azure VM "
  ansible.builtin.include_tasks:    roles-sap-ops/8.0.0-start-sap/tasks/vmrestart.yml
  vars:
    subscriptionId:                "{{ ansible_env.AZURE_SUBSCRIPTION_ID }}"
    resourceGroup_name:            "{{ rgname }}"
    # vmName:                        "{{ item.name }}"
  # loop:           "{{ groups['all'] }}" 
  when:                sap_ops == "START"


  
