
# Start Azure VM.
# - block:
#   # Start the Azure VM
#   - name:                              "Start the VM"
#     azure_rm_virtualmachine:
#      resource_group:                   "{{ sap_system_configuration_name }}"
#      name:                             "{{ansible_hostname }}"
#      restarted:                        true    
    
#   when:
#   -  sap_ops == "start"
# Debug I am here
  - name:                                "Debug I am here"
    ansible.builtin.debug:
      msg:                                "I am here"

  - name:                            "2.10.1 sap-notes: Including Task for VM Agent Actions"
    ansible.builtin.include_tasks:    roles-misc/0.7-VmAgentActions/tasks/main.yaml
    vars:
      subscriptionId:                "{{ ansible_env.AZURE_SUBSCRIPTION_ID }}"
      resourceGroup_name:            "{{ rgname }}"
      # vmName:                        "{{ item.name }}"
    # loop:           "{{ groups['all'] }}" 
    when:                sap_ops == "START"
