---

######################################################################################################
# This playbook is used to reboot all VMs in a resource group when the VM agent status is not ready. #
######################################################################################################

- name:          "Debug display sub and rg"
  ansible.builtin.debug:
    msg:        "subscriptionId: {{ subscriptionId }}, resourceGroup_name: {{ rgname }}"

- name:                                "Get VM list from resource_group: {{ resourceGroup_name }}"
  delegate_to:                         localhost
  become:                              false
  ansible.builtin.command: >-
                                       az vm list --resource-group {{ resourceGroup_name }} \
                                       --subscription {{ subscriptionId }} --query [].name -o tsv
  register:                            rg_vm_list
  changed_when:                        false
  failed_when:                         false

# List the VMs in the resource group
- name:          "Debug List of VMs"
  ansible.builtin.debug:
    msg:        "VM Agent Status: {{ rg_vm_list.stdout_lines}}"

- name:                                "Get the agent status for each VM in resource_group: {{ resourceGroup_name }}"
  block:

    # foreach vm in rg_vm_list, find the agent status and reboot the VM when status is not ready
    - name:                            "Get the agent status for each VM in resource_group: {{ resourceGroup_name }}"
      delegate_to:                     localhost
      become:                          false
      ansible.builtin.command: >-
                                       az vm get-instance-view --name {{ item }} --resource-group {{ resourceGroup_name }} \
                                           --subscription {{ subscriptionId }} \
                                           --query "[name, instanceView.vmAgent.statuses[].displayStatus | [0]]" \
                                           -o tsv
      register:                        vm_agent_status
      changed_when:                    false
      loop:                            "{{ rg_vm_list.stdout_lines }}"
      when:
        - item | length > 2
    
    # - name:          "Debug display sub and rg"
    #   ansible.builtin.debug:
    #    msg:        "VM Agent Status: {{ vm_agent_status[0]}}"

    - name:                            "Reboot VM when agent status is not ready"
      delegate_to:                     localhost
      become:                          false
      ansible.builtin.command: >-
                                       az vm restart --name {{ item }} --resource-group {{ resourceGroup_name }} \
                                           --subscription {{ subscriptionId }}
      when:
        - rg_vm_list is defined
      loop:                            "{{ rg_vm_list }}"
      register:                        vm_reboot
      changed_when:                    false

    - name:                                "Wait for 120 seconds"
      delegate_to:                         localhost
      become:                              false
      ansible.builtin.pause:
        seconds:                           120
      when:                                vm_reboot is changed
  when:
    - rg_vm_list is defined
    - rg_vm_list.rc == 0
    - rg_vm_list.stdout_lines | length > 0
